export const NOTION_COLORS = [
  { id: 'default', name: 'Por defecto', bgVar: 'var(--color-bg-default)', textVar: 'var(--color-text-default)', pillVar: 'var(--color-pill-default)' },
  { id: 'gray', name: 'Gris', bgVar: 'var(--color-bg-gray)', textVar: 'var(--color-text-gray)', pillVar: 'var(--color-pill-gray)' },
  { id: 'brown', name: 'Marrón', bgVar: 'var(--color-bg-brown)', textVar: 'var(--color-text-brown)', pillVar: 'var(--color-pill-brown)' },
  { id: 'orange', name: 'Naranja', bgVar: 'var(--color-bg-orange)', textVar: 'var(--color-text-orange)', pillVar: 'var(--color-pill-orange)' },
  { id: 'yellow', name: 'Amarillo', bgVar: 'var(--color-bg-yellow)', textVar: 'var(--color-text-yellow)', pillVar: 'var(--color-pill-yellow)' },
  { id: 'green', name: 'Verde', bgVar: 'var(--color-bg-green)', textVar: 'var(--color-text-green)', pillVar: 'var(--color-pill-green)' },
  { id: 'blue', name: 'Azul', bgVar: 'var(--color-bg-blue)', textVar: 'var(--color-text-blue)', pillVar: 'var(--color-pill-blue)' },
  { id: 'purple', name: 'Púrpura', bgVar: 'var(--color-bg-purple)', textVar: 'var(--color-text-purple)', pillVar: 'var(--color-pill-purple)' },
  { id: 'pink', name: 'Rosa', bgVar: 'var(--color-bg-pink)', textVar: 'var(--color-text-pink)', pillVar: 'var(--color-pill-pink)' },
  { id: 'red', name: 'Rojo', bgVar: 'var(--color-bg-red)', textVar: 'var(--color-text-red)', pillVar: 'var(--color-pill-red)' },
];

export const LIST_COLORS = NOTION_COLORS.filter(c => c.id !== 'default');

export const LIST_ICONS = [
  { id: 'ShoppingCart', name: 'Carrito' },
  { id: 'Home', name: 'Casa' },
  { id: 'PartyPopper', name: 'Fiesta' },
  { id: 'Plane', name: 'Viaje' },
  { id: 'Gift', name: 'Regalo' },
  { id: 'Utensils', name: 'Comida' },
  { id: 'Backpack', name: 'Mochila' },
  { id: 'Car', name: 'Auto' },
  { id: 'Dog', name: 'Mascota' },
  { id: 'Baby', name: 'Bebé' },
  { id: 'Briefcase', name: 'Trabajo' },
  { id: 'GraduationCap', name: 'Estudios' },
  { id: 'Heart', name: 'Salud' },
  { id: 'Dumbbell', name: 'Deporte' },
  { id: 'Music', name: 'Música' },
  { id: 'Camera', name: 'Fotos' },
  { id: 'Gamepad2', name: 'Juegos' },
  { id: 'Coffee', name: 'Café' },
  { id: 'Pizza', name: 'Pizza' },
  { id: 'IceCream', name: 'Postre' },
  { id: 'Sun', name: 'Sol' },
  { id: 'Moon', name: 'Luna' },
  { id: 'Cloud', name: 'Nube' },
  { id: 'TreeDeciduous', name: 'Árbol' },
  { id: 'Mountain', name: 'Montaña' },
  { id: 'Waves', name: 'Mar' },
  { id: 'Palette', name: 'Arte' },
  { id: 'Brush', name: 'Pintura' },
  { id: 'Pen', name: 'Escritura' },
  { id: 'Book', name: 'Lectura' },
  { id: 'Users', name: 'Usuarios' },
  { id: 'User', name: 'Usuario' },
  { id: 'Calendar', name: 'Calendario' },
  { id: 'Package', name: 'Paquete' },
  { id: 'Wallet', name: 'Billetera' },
  { id: 'CreditCard', name: 'Tarjeta' },
  { id: 'Smartphone', name: 'Celular' },
  { id: 'Laptop', name: 'Laptop' },
  { id: 'Zap', name: 'Energía' },
  { id: 'Droplets', name: 'Agua' },
  { id: 'Flame', name: 'Fuego' },
  { id: 'Hammer', name: 'Herramientas' },
  { id: 'Wrench', name: 'Reparación' },
  { id: 'Shield', name: 'Seguridad' },
  { id: 'Key', name: 'Llave' },
  { id: 'Lock', name: 'Bloqueo' },
];
